CREATE DATABASE sallonccina;

USE sallonccina;

CREATE TABLE funcionarios(
    FUN_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FUN_NOME VARCHAR(100) NOT NULL,
    FUN_CPF VARCHAR(20) NOT NULL,
    FUN_FUNCAO VARCHAR(100) NOT NULL,
    FUN_TEL VARCHAR(20) NOT NULL,
    FUN_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE clientes(
    CLI_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_CPF VARCHAR(20) NOT NULL,
    CLI_TEL VARCHAR(20) NOT NULL,
    CLI_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CLI_DATANASC DATE NOT NULL
);

CREATE TABLE usuarios (
    USU_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USU_LOGIN VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR(100) NOT NULL,
    USU_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    FK_FUN_ID INT NOT NULL

);

CREATE TABLE catalogo(
    CAT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CAT_NOME VARCHAR(100) NOT NULL,
    CAT_DESCRICAO VARCHAR(100) NOT NULL,
    CAT_PRECO DECIMAL(10,2),
    CAT_TEMPO INT NULL,
    CAT_ATIVO BOOLEAN NOT NULL DEFAULT TRUE

);

CREATE TABLE agenda(
    AG_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AG_HORA DATETIME NOT NULL,
    AG_STATUS char(1) NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FK_CAT_ID INT NOT NULL,
    FK_FUN_ID INT NOT NULL
    
);

CREATE TABLE vendas(
    VEN_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VEN_DATAHORA DATETIME NOT NULL, 
    VEN_TOTAL DECIMAL(10,2) NOT NULL,
    FK_AG_ID INT NOT NULL
);

ALTER TABLE usuarios ADD CONSTRAINT USU_FUN FOREIGN KEY (FK_FUN_ID) REFERENCES funcionarios (FUN_ID);
ALTER TABLE agenda ADD CONSTRAINT AGE_CLI FOREIGN KEY (FK_CLI_ID) REFERENCES clientes (CLI_ID);
ALTER TABLE agenda ADD CONSTRAINT AGE_CAT FOREIGN KEY (FK_CAT_ID) REFERENCES catalogo (CAT_ID);
ALTER TABLE agenda ADD CONSTRAINT AGE_FUN FOREIGN KEY (FK_FUN_ID) REFERENCES funcionarios (FUN_ID);
ALTER TABLE vendas ADD CONSTRAINT VEN_AGE FOREIGN KEY (FK_AG_ID) REFERENCES agenda (AG_ID);

ALTER TABLE clientes ADD COLUMN CLI_SENHA VARCHAR(100) NOT NULL;